version: '3.7'

services:

  php:
    image: twenty7/contacts-app:latest
    build: ./
    restart: always
    volumes:
      - ./docker/logs:/var/log
      - ./:/var/www/contacts
      # - ./public:/var/www/contacts/public
    networks:
      - contacts

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - "80:80"
    command: ["/bin/bash", "-c", "sed 's/NGINX_HOST/${NGINX_HOST}/g' /etc/nginx/conf.d/site.conf.tmp > /etc/nginx/conf.d/site.conf && nginx -g 'daemon off;'"]
    volumes:
      - ./:/var/www/contacts:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/site.conf.tmp
      - ./docker/logs:/var/log/nginx
    networks:
      - contacts
    depends_on:
      - php
      - mysql

  mysql:
    image: mysql:5.7
    shm_size: '2gb'
    restart: always
    environment:
      MYSQL_DATABASE: contacts
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    volumes:
      - ./docker/db-data:/var/lib/mysql
      - ./docker/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    networks:
      - contacts
    ports:
      - 3307:3306

networks:
  contacts:
    driver: bridge
